package cl.clasejava.bd_museos.add;

import cl.clasejava.bd_museos.ConexionBD;
import cl.clasejava.bd_museos.JForm;
import javax.swing.*;
import java.sql.*;

/**
 * @author alexblade2001
 */
public class addAuthor extends JForm {
    private final ConexionBD conexionBD;

    /**
     * Creates new form InsertAuthor
     */
    public addAuthor() {
        initComponents();
        conexionBD = ConexionBD.getInstancia();
        getPaises();
        getSexo();
    }

    private void getPaises() {
        try {
            Connection conexion = conexionBD.getConexion();
            try (Statement statement = conexion.createStatement()) {
                String selectQuery = "SELECT nomPais FROM pais_origen";
                ResultSet resultSet = statement.executeQuery(selectQuery);

                // Crear un modelo para el JComboBox
                DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
                comboBoxModel.addElement("Seleccione un pais");
                // Agregar los países al modelo del JComboBox
                while (resultSet.next()) {
                    String pais = resultSet.getString("nomPais");
                    comboBoxModel.addElement(pais);
                }

                // Establecer el modelo del JComboBox
                pais.setModel(comboBoxModel);

                resultSet.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
        private void getSexo() {
        try {
            Connection conexion = conexionBD.getConexion();
            try (Statement statement = conexion.createStatement()) {
                String selectQuery = "SELECT nomSexo FROM sexo";
                ResultSet resultSet2 = statement.executeQuery(selectQuery);

                // Crear un modelo para el JComboBox
                DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
                
                comboBoxModel.addElement("Seleccione el sexo");

                // Agregar los países al modelo del JComboBox
                while (resultSet2.next()) {
                    String sexo = resultSet2.getString("nomSexo");
                    comboBoxModel.addElement(sexo);
                }

                // Establecer el modelo del JComboBox
                sexo.setModel(comboBoxModel);

                //resultSet2.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        apellidoPaterno = new javax.swing.JTextField();
        apellidoMaterno = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        pais = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        fechaNacimiento = new javax.swing.JTextField();

        setTitle("Agregar Autor/a");
        setResizable(false);

        nombre.setPreferredSize(new java.awt.Dimension(128, 20));

        apellidoPaterno.setPreferredSize(new java.awt.Dimension(128, 20));

        apellidoMaterno.setPreferredSize(new java.awt.Dimension(128, 20));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sexo.setPreferredSize(new java.awt.Dimension(128, 20));

        pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pais.setPreferredSize(new java.awt.Dimension(128, 20));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Fecha de Nacimiento");

        jLabel5.setText("Sexo");

        jLabel6.setText("País");

        add.setText("Agregar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pais, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancel)
                            .addComponent(add))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addActionPerformed
        String nombreValue = nombre.getText();
    String apellidoPaternoValue = apellidoPaterno.getText();
    String apellidoMaternoValue = apellidoMaterno.getText();
    String fechaNacimientoValue = fechaNacimiento.getText();
    String sexoValue = (String) sexo.getSelectedItem(); // Obtener el país seleccionado del JComboBox
    String paisValue = (String) pais.getSelectedItem(); // Obtener el país seleccionado del JComboBox
    
    try {
        Connection conexion = conexionBD.getConexion();

        // Obtener el identificador del país seleccionado
        Statement statement = conexion.createStatement();
        
        // Ejecutar la primera consulta (obtener idPais)
        String selectQuery = "SELECT idPais FROM pais_origen WHERE nomPais = '" + paisValue + "'";
        ResultSet resultSet = statement.executeQuery(selectQuery);
        
        // Ejecutar la segunda consulta (obtener idSexo)
        Statement statement2 = conexion.createStatement();
        String selectQuery2 = "SELECT idsexo FROM sexo WHERE nomSexo = '" + sexoValue + "'";
        ResultSet resultSet2 = statement2.executeQuery(selectQuery2);
        
        if (resultSet.next() && resultSet2.next()) {
            int paisId = resultSet.getInt("idPais");
            int sexoId = resultSet2.getInt("idsexo");

            // Insertar los datos en la tabla correspondiente
            String insertQuery = "INSERT INTO autor (nomAut, appAut, apmAut, fechaNac, idSexo, idPais) VALUES ('"
                    + nombreValue + "', '"
                    + apellidoPaternoValue + "', '"
                    + apellidoMaternoValue + "', '"
                    + fechaNacimientoValue + "', "
                    + sexoId + ", "
                    + paisId + ")";
            statement.executeUpdate(insertQuery);

            JOptionPane.showMessageDialog(this, "El autor se ha agregado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el país seleccionado.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Cerrar los ResultSet y Statements
        resultSet.close();
        resultSet2.close();
        statement.close();
        statement2.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al agregar el museo: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    
    dispose();
    }// GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelActionPerformed
        dispose();
    }// GEN-LAST:event_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField apellidoMaterno;
    private javax.swing.JTextField apellidoPaterno;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pais;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables
}
